version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/standard-jobs-fixed.yml

env:
  global:
    - COMPOSER_ROOT_VERSION="4.x-dev"
    - REQUIRE_RECIPE="$COMPOSER_ROOT_VERSION"
